# Generated by Django 5.1.5 on 2025-01-15 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_customuser_username"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"ordering": ["email"], "verbose_name": "Пользователь", "verbose_name_plural": "Пользователи"},
        ),
    ]
