# Generated by Django 5.1.4 on 2025-01-13 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_article_preview"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ["views_counter", "title"],
                "verbose_name": "Публикация",
                "verbose_name_plural": "Публикации",
            },
        ),
    ]
